### ISSUE TITLE
Issue with prompb.TimeSeries

### ISSUE THREAD

**Issue by saket-k-gupta** [shirou/prometheus_remote_kinesis#2]
Hi,
I am getting below issue to build with 1.13.0 version, can you please advice to fix.
./kinesis.go:92:29: cannot use req.Timeseries (type []prompb.TimeSeries) as type []*prompb.TimeSeries in argument to parseRecords

**Comment by mitchellrj** [comment]
in Kinesis.go on line 97 change `[]*prompb.TimeSeries` to `[]prompb.TimeSeries`.

**Comment by shirou** [comment]
perhaps this has been fixed by #3. Thank you @mitchellrj !
